### ISSUE TITLE
AttributeError at /auth/token 

### ISSUE THREAD

**Issue by shaziamuckram** [SAT510/CampusJobReview#14] opened 2024-10-28 17:10 UTC
Client object has no attribute id with post request method

**Comment by shaziamuckram** [comment] 2024-10-29 19:45
@amaygada any update on this fix?

**Comment by amaygada** [comment] 2024-10-30 11:08
Fixed this. Was caused by django's jwt engine looking for id. I changed it such that it looks for the username as a unique field. Works now. Merged into my branch frontend/amay. Creaing a pull request. please accept it.

**Comment by tahreemm** [comment] 2024-10-31 02:21
Changes are visible - closing the issue

**Closed as completed by tahreemm** 2024-10-31 02:21 UTC
Labels: bug
